apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-bff
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - noctem-portfolio
  selector:
    matchLabels:
      app: frontend-bff
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
