apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: noctem-portfolio

resources:
  - ../../base/namespace.yaml
  - ../../base/profile-service
  - ../../base/frontend-bff
  - ../../base/web
  - ingress.yaml
  
images:
  - name: ghcr.io/noctemlabs/profile-service
    newTag: v1.3.5
  - name: ghcr.io/noctemlabs/frontend-bff
    newTag: v1.3.5
  - name: ghcr.io/noctemlabs/web
    newTag: v1.3.5
