apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: noctem-portfolio

resources:
  - ../../base
  - ingress.yaml

images:
  - name: ghcr.io/noctemlabs/profile-service
    newTag: latest
  - name: ghcr.io/noctemlabs/frontend-bff
    newTag: latest
  - name: ghcr.io/noctemlabs/web
    newTag: latest