name: build-images

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Tag
        run: echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3

      - name: Build & push profile-service
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/profile-service.Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/noctemlabs/profile-service:${{ env.TAG }}
            ghcr.io/noctemlabs/profile-service:latest

      - name: Build & push frontend-bff
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/frontend-bff.Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/noctemlabs/frontend-bff:${{ env.TAG }}
            ghcr.io/noctemlabs/frontend-bff:latest
